spring.application.name=lab8

spring.data.mongodb.uri=mongodb://localhost:27017/SBA301DB
spring.data.mongodb.database=SBA301DB

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8